name: auto-testing
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install requirements
        run: |
            sudo apt update
            sudo apt install -y software-properties-common
            sudo add-apt-repository universe
            # Verify installation
            if ! python3 -c "import distutils.msvccompiler" &>/dev/null; then
             echo "Error: python3-distutils failed to install."
             exit 1
            fi

            pip install -r requirements.txt

      - name: Install Node.js and CML
        run: |
          sudo apt-get install -y nodejs npm
          npm install -g @dvcorg/cml
          
      - name: Run pipeline
        env:
          repo_token: ${{ secrets.PAT_SECRET }}
        run: |

          # Your ML workflow goes here

          python test.py
