name: auto-testing
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install requirements
        run: |
          pip install -r requirements.txt

      # - name: Install Node.js and CML
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y nodejs npm
      #     npm install -g @dvcorg/cml


      - name: Run pipeline
        env:
          repo_token: ${{ secrets.PAT_SECRET }}
        run: |
          dvc repro 

          # Your ML workflow goes here

          python test.py
